<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Submit your book for review Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'submission-thanks.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'reviews@LoneStarLiterary.com',
		'to' => 'reviews@LoneStarLiterary.com'
	),
	'fields' => array(
		'custom_U7653' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'DATE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'DATE\' is required.'
			)
		),
		'Email' => array(
			'order' => 20,
			'type' => 'email',
			'label' => 'EMAIL',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'EMAIL\' is required.',
				'format' => 'Field \'EMAIL\' has an invalid email.'
			)
		),
		'custom_U7631' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'BOOK TITLE ',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'BOOK TITLE \' is required.'
			)
		),
		'custom_U7618' => array(
			'order' => 12,
			'type' => 'checkbox',
			'label' => 'Fiction/Poetry (fee $249)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7586' => array(
			'order' => 13,
			'type' => 'checkbox',
			'label' => 'Nonfiction (fee $279)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7606' => array(
			'order' => 22,
			'type' => 'checkbox',
			'label' => 'Sign me up for Lone Star Literary Life news!

Be sure to email your book cover  image and author headshot to Reviews@LoneStarLiterary.com

Click SUBMIT below, and we\'ll invoice you the appropriate amount when your book is approved',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7663' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'ISBN and binding of primary print edition',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'ISBN and binding of primary print edition\' is required.'
			)
		),
		'custom_U7667' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'ISBN and binding of other editions',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7671' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'AUTHOR(S)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'AUTHOR(S)\' is required.'
			)
		),
		'custom_U7675' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'PUBLISHER / IMPRINT',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PUBLISHER / IMPRINT\' is required.'
			)
		),
		'custom_U7679' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'PAGE COUNT',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PAGE COUNT\' is required.'
			)
		),
		'custom_U7683' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'FEATURES (illustrations, maps, index, etc.)',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7687' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'RETAIL PRICE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'RETAIL PRICE\' is required.'
			)
		),
		'custom_U7691' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'PUBLICATION DATE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PUBLICATION DATE\' is required.'
			)
		),
		'custom_U7695' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'SUBJECT',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'SUBJECT\' is required.'
			)
		),
		'custom_U7699' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'PUBLISHER OR AUTHOR CONTACT NAME/TITLE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PUBLISHER OR AUTHOR CONTACT NAME/TITLE\' is required.'
			)
		),
		'custom_U7703' => array(
			'order' => 15,
			'type' => 'string',
			'label' => 'ADDRESS',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'ADDRESS\' is required.'
			)
		),
		'custom_U7707' => array(
			'order' => 16,
			'type' => 'string',
			'label' => 'CITY',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'CITY\' is required.'
			)
		),
		'custom_U7711' => array(
			'order' => 17,
			'type' => 'string',
			'label' => 'STATE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'STATE\' is required.'
			)
		),
		'custom_U7723' => array(
			'order' => 21,
			'type' => 'string',
			'label' => 'ADDITIONAL COMMENTS OR INSTRUCTIONS?',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U7734' => array(
			'order' => 18,
			'type' => 'string',
			'label' => 'ZIP / POSTAL CODE / COUNTRY',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'ZIP / POSTAL CODE / COUNTRY\' is required.'
			)
		),
		'custom_U7738' => array(
			'order' => 19,
			'type' => 'string',
			'label' => 'PHONE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PHONE\' is required.'
			)
		)
	)
);

process_form($form);
?>
