<?php

/* por qué, Drupal? */
include_once 'etype.blocks.inc';

/**
 * @file
 * Custom functions and hooks for Etype Services
 *
 */

/**
 * Implements hook_menu().
 */
function etype_menu() {

  $items = [];

  /* Add first e-Edition link to User Menu */
  $items['e-edition'] = [
    'title' => 'e-Edition',
    'description' => 'Link to e-Edition.',
    'page callback' => '_etype_e_edition',
    'access arguments' => ['access content'],
    'menu_name' => 'menu-secondary-menu',
    'type' => MENU_NORMAL_ITEM,
  ];

  /* admin settings page */
  $items['admin/config/etype'] = [
    'title' => 'eType',
    'description' => 'eType Settings',
    // Like any other menu item
    'position' => 'right',
    'weight' => -15,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => ['administer site configuration'],
    // Permission needed to view this area
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  ];

  $items['admin/config/etype/settings'] = [
    'title' => 'eType Settings',
    'description' => 'eType integration options',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['etype_admin'],
    'file' => 'etype.admin.inc',
    'access arguments' => ['administer site configuration'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * redirect to e-Edition (defaults to first of possible multiple)
 */
function _etype_e_edition() {
  $e_editions = etype_e_editions();
  drupal_goto($e_editions[0]['path']);
}

/**
 * Parse e-Edition settings into an array for use in other functions
 */
function etype_e_editions() {
  $uid = user_is_logged_in();
  $e_edition = variable_get('etype_e_edition');
  $pub = variable_get('etype_pub');
  $ptype = variable_get('etype_ptype');
  $site = variable_get('site_name', 'eType Site');
  $items = explode(',', $e_edition);
  $pubs = explode(',', $pub);
  $ptypes = explode(',', $ptype);
  $e_editions = [];
  $ptr = 0;
  foreach ($items as $item) {
    $arr = explode('|', $item);
    if (isset($arr[1])) {
      $site = trim($arr[1]);
    }

    $ar2 = preg_split("/ID[0-9]+/", $arr[0]); // make LandingImage directory name
    $imagedir = trim($ar2[0]);
    $e_editions[$ptr]['image'] = 'https://etypeservices.com/LandingPageImages/' . $imagedir . '/currentpg1.jpg';

    $pub = trim($pubs[$ptr]);
    $ptype = trim($ptypes[$ptr]);
    $e_edition = trim($arr[0]);

    if ($uid > 0) {
      if (!empty ($pub)) {
        global $user;
        $path = 'https://etypeservices.com/ReadTheEdition.aspx?Username=' . $user->name . "&Pub=" . $pub . "&PType=" . $ptype;
      }
      else {
        $path = 'https://etypeservices.com/' . $e_edition . '/';
      }
    }
    else {
      $path = 'https://etypeservices.com/' . $e_edition . '/';
    }

    $e_editions[$ptr]['site_name'] = trim($site);
    $e_editions[$ptr]['path'] = $path;
    $ptr++;
  }
  return $e_editions;
}
